-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 16:24:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myAPI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myAPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myAPI` DEFAULT CHARACTER SET utf8 ;
USE `myAPI` ;

-- -----------------------------------------------------
-- Table `myAPI`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myAPI`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pseudo` VARCHAR(45) NULL,
  `password` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myAPI`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myAPI`.`video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `duration` INT NULL,
  `user_id` INT NOT NULL,
  `source` VARCHAR(360) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `view` INT NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `file` VARCHAR(360),
  PRIMARY KEY (`id`),
  INDEX `fk_video_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_video_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `myAPI`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myAPI`.`video_format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myAPI`.`video_format` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `uri` VARCHAR(360) NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_video_format_video1_idx` (`video_id` ASC),
  CONSTRAINT `fk_video_format_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `myAPI`.`video` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myAPI`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myAPI`.`token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `expired_at` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_token_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  CONSTRAINT `fk_token_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `myAPI`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myAPI`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myAPI`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` LONGTEXT NULL,
  `user_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_comment_video1_idx` (`video_id` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `myAPI`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `myAPI`.`video` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
